"""
##################################################
# Fedora_API_A_Service_services.py 
# generated by ZSI.generate.wsdl2python
##################################################

    Edited by Benjamin O'Steen

    This file is part of python-fedoracommons.

    python-fedoracommons is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    python-fedoracommons is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with python-fedoracommons.  If not, see <http://www.gnu.org/licenses/>.
"""

__license__ = 'GPL http://www.gnu.org/licenses/gpl.txt'
__author__ = "Benjamin O'Steen <bosteen@gmail.com>"
__version__ = '0.1'

from Fedora_2_0_API_A_Service_services_types import *
import urlparse, types
from ZSI.TCcompound import ComplexType, Struct
from ZSI import client
import ZSI

# Locator
class Fedora_API_A_ServiceLocator:
    Fedora_API_A_address = "http://ora.ouls.ox.ac.uk:8080/fedora/access/soap"
    def getFedora_API_AAddress(self):
        return Fedora_API_A_ServiceLocator.Fedora_API_A_address
    def getFedora_API_A(self, url=None, **kw):
        return access_soapSoapBindingSOAP(url or Fedora_API_A_ServiceLocator.Fedora_API_A_address, **kw)

# Methods
class access_soapSoapBindingSOAP:
    def __init__(self, url, **kw):
        kw.setdefault("readerclass", None)
        kw.setdefault("writerclass", None)
        # no resource properties
        self.binding = client.Binding(url=url, **kw)
        # no ws-addressing

    # op: describeRepository
    def describeRepository(self, request):
        if isinstance(request, describeRepositoryRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://www.fedora.info/definitions/1/0/api/#describeRepository", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=describeRepositoryResponse.typecode.ofwhat, pyclass=describeRepositoryResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: getObjectProfile
    def getObjectProfile(self, request):
        if isinstance(request, getObjectProfileRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://www.fedora.info/definitions/1/0/api/#getObjectProfile", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=getObjectProfileResponse.typecode.ofwhat, pyclass=getObjectProfileResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: listMethods
    def listMethods(self, request):
        if isinstance(request, listMethodsRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://www.fedora.info/definitions/1/0/api/#listMethods", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=listMethodsResponse.typecode.ofwhat, pyclass=listMethodsResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: listDatastreams
    def listDatastreams(self, request):
        if isinstance(request, listDatastreamsRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://www.fedora.info/definitions/1/0/api/#listDatastreams", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=listDatastreamsResponse.typecode.ofwhat, pyclass=listDatastreamsResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: getDatastreamDissemination
    def getDatastreamDissemination(self, request):
        if isinstance(request, getDatastreamDisseminationRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://www.fedora.info/definitions/1/0/api/#getDatastreamDissemination", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=getDatastreamDisseminationResponse.typecode.ofwhat, pyclass=getDatastreamDisseminationResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: getDissemination
    def getDissemination(self, request):
        if isinstance(request, getDisseminationRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://www.fedora.info/definitions/1/0/api/#getDissemination", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=getDisseminationResponse.typecode.ofwhat, pyclass=getDisseminationResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: findObjects
    def findObjects(self, request):
        if isinstance(request, findObjectsRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://www.fedora.info/definitions/1/0/api/#findObjects", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=findObjectsResponse.typecode.ofwhat, pyclass=findObjectsResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: resumeFindObjects
    def resumeFindObjects(self, request):
        if isinstance(request, resumeFindObjectsRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://www.fedora.info/definitions/1/0/api/#resumeFindObjects", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=resumeFindObjectsResponse.typecode.ofwhat, pyclass=resumeFindObjectsResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

    # op: getObjectHistory
    def getObjectHistory(self, request):
        if isinstance(request, getObjectHistoryRequest) is False:
            raise TypeError, "%s incorrect request type" % (request.__class__)
        kw = {}
        # no input wsaction
        self.binding.Send(None, None, request, soapaction="http://www.fedora.info/definitions/1/0/api/#getObjectHistory", encodingStyle="http://schemas.xmlsoap.org/soap/encoding/", **kw)
        # no output wsaction
        typecode = Struct(pname=None, ofwhat=getObjectHistoryResponse.typecode.ofwhat, pyclass=getObjectHistoryResponse.typecode.pyclass)
        response = self.binding.Receive(typecode)
        return response

class describeRepositoryRequest:
    def __init__(self):
        return
describeRepositoryRequest.typecode = Struct(pname=("http://www.fedora.info/definitions/1/0/api/","describeRepository"), ofwhat=[], pyclass=describeRepositoryRequest, encoded="http://www.fedora.info/definitions/1/0/api/")

class describeRepositoryResponse:
    def __init__(self):
        self._response = None
        return
describeRepositoryResponse.typecode = Struct(pname=("http://www.fedora.info/definitions/1/0/api/","describeRepositoryResponse"), ofwhat=[FedoraAPI_2_0_ns.RepositoryInfo_Def(pname="response", aname="_response", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=describeRepositoryResponse, encoded="http://www.fedora.info/definitions/1/0/api/")

class getObjectProfileRequest:
    def __init__(self):
        self._pid = None
        self._asOfDateTime = None
        return
getObjectProfileRequest.typecode = Struct(pname=("http://www.fedora.info/definitions/1/0/api/","getObjectProfile"), ofwhat=[ZSI.TC.String(pname="pid", aname="_pid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="asOfDateTime", aname="_asOfDateTime", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getObjectProfileRequest, encoded="http://www.fedora.info/definitions/1/0/api/")

class getObjectProfileResponse:
    def __init__(self):
        self._response = None
        return
getObjectProfileResponse.typecode = Struct(pname=("http://www.fedora.info/definitions/1/0/api/","getObjectProfileResponse"), ofwhat=[FedoraAPI_2_0_ns.ObjectProfile_Def(pname="response", aname="_response", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getObjectProfileResponse, encoded="http://www.fedora.info/definitions/1/0/api/")

class listMethodsRequest:
    def __init__(self):
        self._pid = None
        self._asOfDateTime = None
        return
listMethodsRequest.typecode = Struct(pname=("http://www.fedora.info/definitions/1/0/api/","listMethods"), ofwhat=[ZSI.TC.String(pname="pid", aname="_pid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="asOfDateTime", aname="_asOfDateTime", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=listMethodsRequest, encoded="http://www.fedora.info/definitions/1/0/api/")

class listMethodsResponse:
    def __init__(self):
        self._response = None
        return
listMethodsResponse.typecode = Struct(pname=("http://www.fedora.info/definitions/1/0/api/","listMethodsResponse"), ofwhat=[FedoraAPI_2_0_ns.ArrayOfObjectMethodsDef_Def(pname="response", aname="_response", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=listMethodsResponse, encoded="http://www.fedora.info/definitions/1/0/api/")

class listDatastreamsRequest:
    def __init__(self):
        self._pid = None
        self._asOfDateTime = None
        return
listDatastreamsRequest.typecode = Struct(pname=("http://www.fedora.info/definitions/1/0/api/","listDatastreams"), ofwhat=[ZSI.TC.String(pname="pid", aname="_pid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="asOfDateTime", aname="_asOfDateTime", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=listDatastreamsRequest, encoded="http://www.fedora.info/definitions/1/0/api/")

class listDatastreamsResponse:
    def __init__(self):
        self._response = None
        return
listDatastreamsResponse.typecode = Struct(pname=("http://www.fedora.info/definitions/1/0/api/","listDatastreamsResponse"), ofwhat=[FedoraAPI_2_0_ns.ArrayOfDatastreamDef_Def(pname="response", aname="_response", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=listDatastreamsResponse, encoded="http://www.fedora.info/definitions/1/0/api/")

class getDatastreamDisseminationRequest:
    def __init__(self):
        self._pid = None
        self._dsID = None
        self._asOfDateTime = None
        return
getDatastreamDisseminationRequest.typecode = Struct(pname=("http://www.fedora.info/definitions/1/0/api/","getDatastreamDissemination"), ofwhat=[ZSI.TC.String(pname="pid", aname="_pid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="dsID", aname="_dsID", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="asOfDateTime", aname="_asOfDateTime", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getDatastreamDisseminationRequest, encoded="http://www.fedora.info/definitions/1/0/api/")

class getDatastreamDisseminationResponse:
    def __init__(self):
        self._response = None
        return
getDatastreamDisseminationResponse.typecode = Struct(pname=("http://www.fedora.info/definitions/1/0/api/","getDatastreamDisseminationResponse"), ofwhat=[FedoraAPI_2_0_ns.MIMETypedStream_Def(pname="response", aname="_response", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getDatastreamDisseminationResponse, encoded="http://www.fedora.info/definitions/1/0/api/")

class getDisseminationRequest:
    def __init__(self):
        self._pid = None
        self._bDefPid = None
        self._methodName = None
        self._parameters = None
        self._asOfDateTime = None
        return
getDisseminationRequest.typecode = Struct(pname=("http://www.fedora.info/definitions/1/0/api/","getDissemination"), ofwhat=[ZSI.TC.String(pname="pid", aname="_pid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="bDefPid", aname="_bDefPid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="methodName", aname="_methodName", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), FedoraAPI_2_0_ns.ArrayOfProperty_Def(pname="parameters", aname="_parameters", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TC.String(pname="asOfDateTime", aname="_asOfDateTime", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getDisseminationRequest, encoded="http://www.fedora.info/definitions/1/0/api/")

class getDisseminationResponse:
    def __init__(self):
        self._response = None
        return
getDisseminationResponse.typecode = Struct(pname=("http://www.fedora.info/definitions/1/0/api/","getDisseminationResponse"), ofwhat=[FedoraAPI_2_0_ns.MIMETypedStream_Def(pname="response", aname="_response", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getDisseminationResponse, encoded="http://www.fedora.info/definitions/1/0/api/")

class findObjectsRequest:
    def __init__(self):
        self._resultFields = None
        self._maxResults = None
        self._query = None
        return
findObjectsRequest.typecode = Struct(pname=("http://www.fedora.info/definitions/1/0/api/","findObjects"), ofwhat=[FedoraAPI_2_0_ns.ArrayOfString_Def(pname="resultFields", aname="_resultFields", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), ZSI.TCnumbers.InonNegativeInteger(pname="maxResults", aname="_maxResults", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True), FedoraAPI_2_0_ns.FieldSearchQuery_Def(pname="query", aname="_query", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=findObjectsRequest, encoded="http://www.fedora.info/definitions/1/0/api/")

class findObjectsResponse:
    def __init__(self):
        self._response = None
        return
findObjectsResponse.typecode = Struct(pname=("http://www.fedora.info/definitions/1/0/api/","findObjectsResponse"), ofwhat=[FedoraAPI_2_0_ns.FieldSearchResult_Def(pname="response", aname="_response", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=findObjectsResponse, encoded="http://www.fedora.info/definitions/1/0/api/")

class resumeFindObjectsRequest:
    def __init__(self):
        self._sessionToken = None
        return
resumeFindObjectsRequest.typecode = Struct(pname=("http://www.fedora.info/definitions/1/0/api/","resumeFindObjects"), ofwhat=[ZSI.TC.String(pname="sessionToken", aname="_sessionToken", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=resumeFindObjectsRequest, encoded="http://www.fedora.info/definitions/1/0/api/")

class resumeFindObjectsResponse:
    def __init__(self):
        self._response = None
        return
resumeFindObjectsResponse.typecode = Struct(pname=("http://www.fedora.info/definitions/1/0/api/","resumeFindObjectsResponse"), ofwhat=[FedoraAPI_2_0_ns.FieldSearchResult_Def(pname="response", aname="_response", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=resumeFindObjectsResponse, encoded="http://www.fedora.info/definitions/1/0/api/")

class getObjectHistoryRequest:
    def __init__(self):
        self._pid = None
        return
getObjectHistoryRequest.typecode = Struct(pname=("http://www.fedora.info/definitions/1/0/api/","getObjectHistory"), ofwhat=[ZSI.TC.String(pname="pid", aname="_pid", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getObjectHistoryRequest, encoded="http://www.fedora.info/definitions/1/0/api/")

class getObjectHistoryResponse:
    def __init__(self):
        self._response = None
        return
getObjectHistoryResponse.typecode = Struct(pname=("http://www.fedora.info/definitions/1/0/api/","getObjectHistoryResponse"), ofwhat=[FedoraAPI_2_0_ns.ArrayOfString_Def(pname="response", aname="_response", typed=False, encoded=None, minOccurs=1, maxOccurs=1, nillable=True)], pyclass=getObjectHistoryResponse, encoded="http://www.fedora.info/definitions/1/0/api/")
